### ISSUE TITLE
Amulet of Yendor from previous adventurer

### ISSUE THREAD

**Issue by transcendreamer** [k21971/EvilHack#100]
I was Infidel and I died. Then in the next run I've found my grave and the Amulet among other items. Once identified it is now cursed cheap plastic imitation but it was a real Amulet in previous life. Not sure if this is a real issue, but just not very logically consistent. How real Amulet becomes a cheap piece of plastic? Well evil magic maybe. 

P.S. I admire you nethack fork. It's very cool and challenging.

**Comment by Umbire** [comment]
It's because the Amulet of Yendor is guaranteed to appear in every game, whether you start with it as an Infidel or seek to grab it from the Sanctum with any other role - having the real Amulet appear in bones would be a nonsensical thing to do since it allows you to essentially cheese your way to the Elemental Planes.

**Comment by transcendreamer** [comment]
I understand it's intended because of game mechanics. I will think it's Wizard's trick for future. :)

**Comment by k21971** [comment]
Glad you're enjoying EvilHack! To reenforce what Umbire said - neither the Amulet of Yendor nor any of the invocation objects will ever appear in bones from a previous game, for hopefully obvious reasons. Closing this as it's not an issue/bug.
