### ISSUE TITLE
Should You retain martial arts as an (unchanging) vampire?

### ISSUE THREAD

**Issue by jkoudys** [k21971/EvilHack#172]
Tested playing as a monk, reaching Grand Master in martial arts and enjoying the 3 (two hands and a kick) attacks a turn. I tried forcing the sentient arise as a vampire, but only get one regular claw attack and a bite. Obviously this is a major downgrade over Grand Master. I can see arguments either way: vampires are monsters and have a special monster attack (the level-draining bite). But they're also physiologically human to the point where they leave human corpses, and aren't lumbering zombies or mummies who would lack the agility to do a roundhouse kick. If anything vampires tend to be much more agile than non-undead humans in fiction.

**Comment by k21971** [comment]
We discussed this a bit today in irc/discord. If you were to just polymorph into a vampire or other humanoid, I would say no to that (having martial arts skill carry over), as that's basically akin to having your cake and eating it too. However, the specific case you're referring to - killed by a vampire, and instead of dying, arising as one and able to continue playing - I could see that being a thing. Especially because at that point, you're now stuck in that form permanently. Interesting. I'll think on this a bit. Thanks for bringing it up @jkoudys

**Comment by jkoudys** [comment]
Perhaps a sentient_arise shouldn't (always) be a simple polymorph, but something closer to the race change a crowned infidel gets? Some types seem fine as an unchanging polyform (eg the green slime), while vampires, vampire mages, revenants, maybe zombies and mummies, could be race changes. The unchanging on a vamp even still has the `#monster` but it simply fails. It could also be a way to turn off reflexive attacks that would cause stoning, similar to the poison tail turned off on infidels vs cockatrices.

Maybe it would count as a stupid ascension trick, but it could be a neat endgame buff to go for as a human wizard. Collect a heap of amulets of lifesaving from polypiling, let a vampire mage bite you, and hope you get your 5% chance of becoming a vampire mage each time. Would be cool in that case because it's a high-cost, high-reward upgrade of intrinsic regen, drain resistance, flying, an extra bite attack, and reflexive offensive magic.

**Comment by k21971** [comment]
I'm not making any changes to this right now. A Monk poly'd into a vampire, and retaining martial arts fighting ability while enjoying the added benefits of a vampire's level-draining bite attack feels too over-powered. I imagine that's the reason we don't see this behavior anywhere else.
