### ISSUE TITLE
Shadowblade evades grasp for non-Chaotics

### ISSUE THREAD

**Issue by jkoudys** [k21971/EvilHack#173]
Does it make sense that an e.g. human neutral tourist should be unable to wield Shadowblade? They'd be able to wield Stormbringer with only the usual blast damage. Its partner in forging is Werebane, which is a basic unaligned artifact weapon. I could understand why a werecreature should have trouble with Shadowblade. I'm even getting blasted by it as a chaotic.

Forged artifacts tend to either retain the alignment and class of one/both the base items, or they become less restrictive (eg Tempest is unaligned from two neutral artifacts). It seems like an oversight that only one forged artifact could suddenly be unwieldable by someone who could wield both the base weapons.

**Comment by Umbire** [comment]
Shadowblade is intelligent and drow-favoring, so my wager is this causes alignment to come up for being able to carry it, as with quest artifacts.

**Comment by loggersviii** [comment]
The reason this happens is pretty straightforward: basically, it’s because Shadowblade is aligned with both an alignment (chaotic), and a race (Drow). It’s similar to how quest artifacts work. For example, if you’re a neutral wizard you will still get blasted by the orb of fate, and as a chaotic wizard you can’t pick it up. Its the same with shadowblade, if you have the same alignment as shadowblade but aren’t drow, you’ll get blasted, and if you aren’t chaotic or a drow, you can’t pick it up.

I think this is pretty lame, but just wanted to say why it was happening. I’d kind of like to see this changed, but it’s not my decision.

**Comment by jkoudys** [comment]
Makes sense. The most frustrating part wasn't not being able to use my helm of opposite alignment to give my dagger-toting tourist a good weapon, it was being a human rogue and getting blasted by the weapon that's basically the signature weapon of the rogue.

**Comment by k21971** [comment]
When I made Shadowblade, the thought behind it was that it would be the signature blade for a Drow Rogue.

I'll play around with some changes and see what feels right.

**Comment by k21971** [comment]
I had another long look at this. Initial intent will remain - if you're not chaotic, or a Drow, you won't be able to wield Shadowblade.
