### ISSUE TITLE
A followup to my Moloch crowning proposal

### ISSUE THREAD

**Issue by Tomsod** [k21971/EvilHack#63]
It seems I've been hasty with c94a7be, as I just realized it probably should also check that the wielded item is a melee weapon.  Currently, Moloch can also add the fire oprop to launchers (would that even work?) and missiles (not a big deal, but what're you gonna do with just one arrow of fire?)  Also, the code immediately below blesses the wielded weapon; Moloch should probably curse it instead.

**Comment by Tomsod** [comment]
Oh, and looking at the code closely, it doesn't really support two elemental oprops at once, as neither the damage nor messages will stack.  Oops?  Probably it will be necessary to further restrict the hellfire blessing to `!(obj->oprops & (ITEM_FIRE | ITEM_FROST | ITEM_SHOCK | ITEM_VENOM))`.

**Comment by k21971** [comment]
We've been discussing this in IRC this morning. Adding the various elemental object properties to launchers is not allowed (for discussions sake: in other variants with object properties, it is). I agree for Infidels the wielded weapon should be cursed instead of blessed. As far as further restrictions go - there really should be a guard against adding an extra object property to a weapon that already has one. I'd change `!(obj->oprops & ITEM_FIRE)` to just `!obj->oprops`

**Comment by Tomsod** [comment]
Or you can just delete any existing property that is not fire.

**Comment by k21971** [comment]
Closed via git commit fdf6158.

**Comment by Tomsod** [comment]
I've reviewed fdf6158, not sure if there're automatic notifications about that.
